name: Immortal Build for JIDU6101 and JIDU6J01

on:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # At 12:00 AM


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        device:
          - name: jidu6101
            config: configs/.config-jidu6101
          - name: jidu6j01 # jidu6201/6401/6601/6701
            config: configs/.config-jidu6j01

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Do Build
      env:
        DEVICE_CONFIG: ${{ matrix.device.config }}
      run: chmod +x build-immortal.sh; bash build-immortal.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-${{ matrix.device.name }}
        path: immortalwrt/bin/targets/mediatek/filogic/immortalwrt*.bin